### ISSUE TITLE
Change name of build job for Identity

### ISSUE THREAD

**Issue by meker12** [deconst/strider-deconst-content#1]
@smashwilson I removed the version from the github Identity doc source repo name.  Wanted to update the Strider build name, but I don't seem to have permission to change it.

When I go to the config panel for the project, I get a blank page: http://ci.deconst.horse/rackerlabs/docs-cloud-identity-2.0/config

**Comment by smashwilson** [comment]
Sometimes I need to refresh to get the config page to show up. It's annoying.

You also can't change the name of the project like that, because it's linked in to the GitHub provider configuration (which repo it pulls from and uses for all of its GitHub API calls and webhook settings). We'd need to delete and recreate the build.

We don't actually have to do that though - GitHub will redirect just fine until I can get the builds configured automatically and set up a new, more permanent Strider environment for the cluster.

**Comment by smashwilson** [comment]
It's [correct](https://build.developer.rackspace.com/rackerlabs/docs-cloud-identity/) on the new infrastructure. :+1:
